added initial studio details

diff --git a/scripts/susestudio b/scripts/susestudio
--- a/scripts/susestudio
+++ b/scripts/susestudio
@@ -1,69 +1,73 @@
 #!/bin/bash
 #############################################################
-# Name:        SUSE Studio Supportconfig Plugin
+# Name:        Supportconfig Plugin for SUSE Studio
 # Description: Gathers important troubleshooting information
 #              about SUSE Linux Enterprise Studio
 # License:     GPLv2
 # Author:      Jason Record (jrecord@novell.com)
-# Modified:    2010 Jul 17
+# Modified:    2010 Sep 16
 #############################################################
 
-SVER=0.0.0
-LOG_LINES=0	#0 means include the entire file
-unset FILES
+SVER=0.0.1
 RCFILE="/opt/supportconfig/resources/scplugin.rc"
+LOG_LINES=500	#0 means include the entire file
+LOG_DIR="/var/log/simba"
+CONF_DIR="/var/lib/simba/sbs/conf"
 
 [ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
 
-section_header SLEPOS Supportconfig Plugin, v${SVER}
-pconf_files /etc/slepos-release
+section_header "Supportconfig Plugin for SUSE Studio, v${SVER}"
+RPMLIST="susestudio-ui-server susestudio-thoth sle-studioonsite-release susestudio-rmds flashpolicyd-studio susestudio-common susestudio susestudio-masquerade susestudio-clicfs susestudio-image-helpers susestudio-testdrive Susestudio-kiwi-runner nagios-www nagios-plugins-extras nagios Nagios-plugins munin Munin-node clicfs"
 
-#t - Branchserver
-section_header "SLEPOS: Branch Server"
-if rpm -q POS_Server-BranchT &>/dev/null; then
-	plugin_command $OF 'ls -la /srv/SLEPOS/*'
-	plugin_command $OF 'ls -la /srv/tftpboot/*'
-
-	test -d /srv/tftpboot/CR/ && FILES=$(find /srv/tftpboot/CR/ -type f) || unset FILES
-	pconf_files $FILES
-
-	test -d /srv/tftpbot/upload/ && FILES=$(find /srv/tftpboot/upload/ -type f | grep hwtype ) || unset FILES
-	pconf_files $FILES /srv/tftpboot/boot/pxelinux.cfg
-
-	test -d /etc/SLEPOS/ && FILES=$(find /etc/SLEPOS/ -type f| grep -v "/etc/SLEPOS/template/" | grep -v "/etc/SLEPOS/installation.xml") || unset FILES
-	pconf_files $FILES /var/lib/dhcp/db/dhcpd.leases
-else
-	plugin_message "# Not Installed"
-	plugin_message
+if rpm -q susestudio susestudio-common &>/dev/null; then
+  echo "ERROR: SUSE Studio package(s) not installed"
+  echo
+  exit 111
 fi
 
-# Adminserver
-section_header "SLEPOS: Admin Server"
-if rpm -q POS_Server-Admin3 &>/dev/null; then
-	plugin_command "slapcat -d 0 | sed -e 's/userPassword::.*/userPassword:: REMOVED/g'"
-else
-	plugin_message "# Not Installed"
-	plugin_message
+for THISRPM in $RPMLIST
+do
+   validate_rpm $THISRPM
+done
+
+plugin_command "cat /proc/meminfo"
+plugin_command "df -h"
+
+section_header "Apache"
+
+section_header "UI Server"
+pconf_files "/srv/studio/options.yml"
+plog_files $LOG_LINES "/srv/studio/ui-server/log/cron_job.log /srv/studio/ui-server/log/production.log /srv/studio/ui-server/log/scheduler.log"
+
+section_header "Testdrive"
+pconf_files "/srv/studio/testdrive/config/options.yml"
+plog_files $LOG_LINES "/srv/studio/testdrive/log/production.log"
+
+section_header "Kiwi Runner"
+pconf_files "/srv/studio/kiwi-runner/config/options.yml"
+plog_files $LOG_LINES "/srv/studio/kiwi-runner/log/backgroundrb.log /srv/studio/kiwi-runner/log/production.log"
+
+section_header "RMDS"
+pconf_files "/srv/studio/rmds.conf"
+plugin_command "grep rmds /var/log/messages | grep -v Ping | grep -v Destroying\ socket"
+
+section_header "THOTH"
+pconf_files "/srv/studio/thoth.conf"
+plugin_command "grep thoth /var/log/messages"
+
+section_header "Nagios"
+pconf_files "/etc/nagios/nagios.cfg /etc/nagios/objects/contacts.cfg"
+
+section_header "Munin"
+pconf_files "/etc/munin/munin.conf"
+
+section_header "Apache Logs"
+plog_files $LOG_LINES "/var/log/apache2/rcapache2.out /var/log/apache2/error_log"
+
+section_header "Appliance Build Logs"
+[ -d /studio/runner/log ] && FILES=$(find /studio/runner/log -type f) || FILES=""
+if [ -n "$FILES" ]; then
+	plog_files $LOG_LINES $FILES
 fi
 
-# Imageserver
-section_header "SLEPOS: Image Server"
-if rpm -q POS_Image3 &>/dev/null; then
-	if [ -d /var/lib/SLEPOS/system/ ]; then 
-		FILES=$(find /var/lib/SLEPOS/system/ -maxdepth 1 -type d | grep -v /var/lib/SLEPOS/system/chroot | grep -v /var/lib/SLEPOS/system/images | grep -v "system\/$") || unset FILES
-		plugin_command $OF "ls -la $FILES"
-	
-		FILES=$(find /var/lib/SLEPOS/system/ -name config.xml)
-		pconf_files $FILES
 
-		FILES=$(find /var/lib/SLEPOS/system/ -name config.sh)
-		pconf_files $FILES
-
-		FILES=$(find /var/lib/SLEPOS/system/ -name images.sh)
-		pconf_files $FILES
-	fi
-else
-	plugin_message "# Not Installed"
-	plugin_message
-fi
-section_header Done
